#!/usr/bin/env python3
"""
Sweep cross_pollination_m ∈ {1,2,4} × epsilon ∈ {0.1,0.2,0.3} with min_probe_fraction=0.3, K=100.
Metrics per (M, eps), averaged over 20 query vectors:
  - clustersProbed   = sum across 4 partitions of nprobe = floor(candidatesAfterEpsilon × 0.3)
  - distComps        = sum across 4 partitions of [NavStats] distComps
  - navPagePins      = sum across 4 partitions of [NavStats] pagePins (nav phase only)
  - diskPageReads    = bufferCachePageReadCount from response (data-page reads = pin misses)
  - cacheHitRatio    = bufferCacheHitRatio from response
  - duplicatesFiltered = [DistinctStats] filteredOut (proves dedup work)
  - recall@100       = |knn_top100 ∩ ann_top100| / 100
  - annLatencyMs     = client-side wall time
"""
import json, urllib.parse, urllib.request, sys, time, re, math, os, csv
from datetime import date

# Script lives at <repo>/cross-pollination/sweep_xpoll_eps.py — so <repo>/debug.log is one
# level up, and the artifact directory is this script's own directory. Both resolve correctly
# regardless of where the repo is cloned (laptop vs. remote box), and the cluster is always
# expected to be on the same host as the script (localhost:19002).
_HERE = os.path.dirname(os.path.abspath(__file__))
URL = "http://localhost:19002/query/service"
LOG = os.path.normpath(os.path.join(_HERE, "..", "debug.log"))
OUT_DIR = _HERE
RUN_TAG = os.environ.get("SWEEP_TAG", f"xpoll_eps_{date.today().isoformat()}")
# Primary-key field name on the Movies dataset. Defaults to "id"; override to e.g. "k" for
# datasets with an autogenerated UUID PK:   PK_FIELD=k python3 sweep_xpoll_eps.py
PK_FIELD = os.environ.get("PK_FIELD", "id")
K   = 100
N   = 20
MIN_PROBE_FRACTION = 0.3
K_MULTIPLIER = 2

NAV_RE = re.compile(
    r"\[NavStats\] findCloseCentroidsLevelWiseGlobalSort: "
    r"pagePins=(\d+), distComps=(\d+), candidatesBeforeEpsilon=(\d+), "
    r"candidatesAfterEpsilon=(\d+), epsilon=([\d.]+)")
DIST_RE = re.compile(
    r"\[DistinctStats\] PreclusteredGroupWriter: "
    r"inputTuples=(\d+), groupsEmitted=(\d+), filteredOut=(\d+), groupFields=(\d+)")

def run(stmt, timeout=300):
    data = urllib.parse.urlencode({"statement": stmt}).encode()
    req  = urllib.request.Request(URL, data=data,
            headers={"Content-Type": "application/x-www-form-urlencoded"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", "replace")
        return {"status": "fatal", "errors": [{"code": e.code, "msg": body[:500]}]}

def log_size():
    try: return os.path.getsize(LOG)
    except OSError: return 0

def log_tail_since(start):
    end = log_size()
    if end <= start: return ""
    with open(LOG, "rb") as f:
        f.seek(start)
        return f.read(end - start).decode("utf-8", "replace")

def vec_literal(v):
    return "[" + ",".join(repr(float(x)) for x in v) + "]"

def knn_query(qvec):
    return f"""
USE MovieDB;
LET qvec={vec_literal(qvec)}
FROM Movies m
SELECT m.{PK_FIELD}
ORDER BY euclidean_squared_distance(m.embedding, qvec)
LIMIT {K};
"""

def ann_query(qvec):
    return f"""
USE MovieDB;
LET qvec={vec_literal(qvec)}
FROM Movies m
SELECT m.{PK_FIELD}
ORDER BY ann_distance(m.embedding, qvec, "euclidean_squared", {MIN_PROBE_FRACTION}, {K_MULTIPLIER})
LIMIT {K};
"""

def create_index_stmt(m, eps):
    return f"""
USE MovieDB;
CREATE INDEX ix1 ON Movies(embedding VECTOR) TYPE VTREE
WITH {{
  "dimension": 384,
  "train_list_fraction": 0.1,
  "similarity": "euclidean_squared",
  "epsilon": {eps},
  "cross_pollination_m": {m}
}} EXCLUDE UNKNOWN KEY;
"""

def drop_index_stmt():
    return "USE MovieDB; DROP INDEX Movies.ix1 IF EXISTS;"

# --- Step 1: sample 20 query vectors ---
print(f"Sampling {N} query embeddings …", flush=True)
sample = run(f"""
USE MovieDB;
FROM Movies m WHERE m.embedding IS KNOWN
SELECT m.{PK_FIELD}, m.embedding
ORDER BY m.{PK_FIELD}
LIMIT {N*50};
""")
if sample.get("status") != "success":
    print("sample failed:", sample.get("errors")); sys.exit(1)
sample_rows = sample["results"][::50][:N]
print(f"  qids = {[r[PK_FIELD] for r in sample_rows]}")

# --- Step 2: ensure no index exists, then KNN ground truth ---
print("\nDropping any existing ix1 …", flush=True)
r = run(drop_index_stmt())
if r.get("status") != "success":
    print("drop:", r.get("errors"))
time.sleep(0.5)

print(f"Running KNN ground truth (no index) for {N} queries …", flush=True)
knn_truth = {}
knn_total_ms = 0
for r in sample_rows:
    qid, qvec = r[PK_FIELD], r["embedding"]
    t0 = time.time()
    res = run(knn_query(qvec))
    knn_total_ms += (time.time() - t0) * 1000
    if res.get("status") != "success":
        print(f"  KNN failed for qid={qid}: {res.get('errors')}"); sys.exit(1)
    knn_truth[qid] = {row[PK_FIELD] for row in res["results"]}
print(f"  KNN avg latency = {knn_total_ms/N:.0f} ms")

# --- Step 3: sweep ---
combos = [(m, eps) for m in [1, 2, 4, 8] for eps in [0.1, 0.2, 0.3, 0.4]]
results = []
raw_records = []  # one entry per (M, eps, qid) — saved to JSON at end

for M_val, eps_val in combos:
    label = f"M={M_val}, eps={eps_val}"
    print(f"\n=== {label} ===", flush=True)
    # build index
    t0 = time.time()
    r = run(create_index_stmt(M_val, eps_val), timeout=300)
    create_ms = (time.time() - t0) * 1000
    if r.get("status") != "success":
        print("  CREATE INDEX failed:", r.get("errors")); sys.exit(1)
    print(f"  CREATE INDEX done in {create_ms:.0f} ms")

    agg = dict(clustersProbed=0, distComps=0, navPagePins=0, diskPageReads=0,
               cacheHitSum=0.0, duplicatesFiltered=0, candidatesAfter=0,
               recallSum=0.0, annMs=0.0, n=0, createMs=create_ms)

    for r in sample_rows:
        qid, qvec = r[PK_FIELD], r["embedding"]
        log_before = log_size()
        t0 = time.time()
        ann = run(ann_query(qvec))
        ann_ms = (time.time() - t0) * 1000
        if ann.get("status") != "success":
            print(f"  ANN failed for qid={qid}: {ann.get('errors')}"); continue

        # Recall
        ann_ids = {row[PK_FIELD] for row in ann["results"]}
        recall = len(knn_truth[qid] & ann_ids) / K

        # Response metrics
        m = ann.get("metrics", {})
        disk_reads = m.get("bufferCachePageReadCount", 0)
        hit_pct = float(m.get("bufferCacheHitRatio", "0%").rstrip("%")) / 100.0

        # Log scrape for nav + distinct stats
        tail = log_tail_since(log_before)
        nav_lines = NAV_RE.findall(tail)
        dist_lines = DIST_RE.findall(tail)

        nav_pins = sum(int(x[0]) for x in nav_lines)
        nav_dists = sum(int(x[1]) for x in nav_lines)
        candidates_after = sum(int(x[3]) for x in nav_lines)
        nprobe_total = sum(math.floor(int(x[3]) * MIN_PROBE_FRACTION) for x in nav_lines)
        filtered = sum(int(x[2]) for x in dist_lines)

        agg["clustersProbed"]   += nprobe_total
        agg["distComps"]        += nav_dists
        agg["navPagePins"]      += nav_pins
        agg["diskPageReads"]    += disk_reads
        agg["cacheHitSum"]      += hit_pct
        agg["duplicatesFiltered"] += filtered
        agg["candidatesAfter"]  += candidates_after
        agg["recallSum"]        += recall
        agg["annMs"]            += ann_ms
        agg["n"]                += 1
        # raw per-query record
        raw_records.append(dict(M=M_val, epsilon=eps_val, qid=qid,
                                clustersProbed=nprobe_total, distComps=nav_dists,
                                navPagePins=nav_pins, diskPageReads=disk_reads,
                                cacheHitPct=hit_pct, duplicatesFiltered=filtered,
                                candidatesAfter=candidates_after,
                                recall=recall, annLatencyMs=ann_ms))

    # average per query
    n = agg["n"]
    if n == 0:
        print("  no successful queries"); continue
    avg = {k: (v / n) for k, v in agg.items() if k != "n"}
    avg["n"] = n
    avg["M"] = M_val
    avg["eps"] = eps_val
    avg["recall"] = avg["recallSum"]
    results.append(avg)
    print(f"  avg clustersProbed={avg['clustersProbed']:.1f}  distComps={avg['distComps']:.0f}  "
          f"navPagePins={avg['navPagePins']:.0f}  diskPageReads={avg['diskPageReads']:.0f}  "
          f"hitRatio={avg['cacheHitSum']:.2%}  recall={avg['recall']:.4f}  annMs={avg['annMs']:.0f}")

    # drop for next iteration
    r = run(drop_index_stmt())
    if r.get("status") != "success":
        print("  drop:", r.get("errors"))

# --- Step 4: print table ---
print("\n\n============================== SUMMARY (averaged over 20 queries) ==============================\n")
hdr = f"{'M':>3} {'ε':>4} | {'clustProbed':>11} {'distComps':>9} {'navPins':>8} {'diskRds':>8} {'hit%':>5}  {'dupsFilt':>8} | {'recall':>7} {'lat(ms)':>7}"
print(hdr)
print("-" * len(hdr))
for r in results:
    print(f"{r['M']:>3} {r['eps']:>4.2f} | {r['clustersProbed']:>11.1f} {r['distComps']:>9.0f} "
          f"{r['navPagePins']:>8.0f} {r['diskPageReads']:>8.0f} {r['cacheHitSum']*100:>4.1f}%  "
          f"{r['duplicatesFiltered']:>8.0f} | {r['recall']:>7.4f} {r['annMs']:>7.0f}")
print()

# --- Step 5: persist artifacts ---
os.makedirs(OUT_DIR, exist_ok=True)
csv_path  = os.path.join(OUT_DIR, f"sweep_{RUN_TAG}.csv")
json_path = os.path.join(OUT_DIR, f"sweep_{RUN_TAG}_raw.json")

with open(csv_path, "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["M", "epsilon", "clustersProbed", "distComps", "navPagePins",
                "diskPageReads", "cacheHitPct", "duplicatesFiltered", "recall", "annLatencyMs"])
    for r in results:
        w.writerow([r["M"], r["eps"],
                    round(r["clustersProbed"], 2),
                    round(r["distComps"], 1),
                    round(r["navPagePins"], 1),
                    round(r["diskPageReads"], 1),
                    round(r["cacheHitSum"] * 100, 2),
                    round(r["duplicatesFiltered"], 1),
                    round(r["recall"], 4),
                    round(r["annMs"], 1)])

with open(json_path, "w") as f:
    json.dump(dict(
        run_tag=RUN_TAG,
        min_probe_fraction=MIN_PROBE_FRACTION, k_multiplier=K_MULTIPLIER, K=K, N=N,
        pk_field=PK_FIELD,
        query_ids=[r[PK_FIELD] for r in sample_rows],
        averaged=[{k: v for k, v in r.items() if k not in ("recallSum", "cacheHitSum")} for r in results],
        per_query=raw_records,
    ), f, indent=2)

print(f"Wrote {csv_path}\nWrote {json_path}")
